audit_header: false
title: Naples Real Estate Video Blog with Vincent Napoleon
description: Our mission at Kimberly Vincent Luxury Real Estate Team is to be your best resource for Naples real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from Kimberly Vincent Luxury Real Estate Team, your professional Naples Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Vincent Napoleon
  title:
  license_number:
  about_markdown: |
    Vincent has been a full-time resident of Naples, Florida for over 30 years. As a real estate investor and professional, Vincent has an extensive background in marketing, finance, and real estate. He uses all these skills to provide world-class service, encompassing all past and present knowledge sets for the benefit of his clients.

    Kimberly takes great joy in sharing her intimate knowledge and valued perspective into the Greater Naples real estate market. Specializing in Residential, Luxury, Condominium and Waterfront Properties and Golf Communities; Kimberly truly loves to provide each client with individual attention, enthusiasm, and insightful awareness into the rich and charming character that the coastal lifestyle has to offer! Kimberly excels at providing insightful, comprehensive guidance and marketing applications that produce results. Regardless of the time and effort it takes, her sole focus is on her client’s ultimate goal of purchasing a home that they will cherish for years.

  brand: Luxury Real Estate by Kimberly & Vincent
  brokerage: Compass
  market: Naples
  address: '800 Laurel Oaks Dr., Suite 400<br>Naples, FL 34108'
  phone: 239-398-6336
  phone_type:
  phone2:
  phone2_type:
  email: vincent.napoleon@gmail.com
  url: http://www.ournaplesflorida.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.napoleonluxuryrealestate.com/form-cma.php
  second_CTA_text: Home Search
  second_CTA_URL: http://napoleonluxuryrealestate.idxbroker.com/idx/search/advanced

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Naples Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.napoleonluxuryrealestate.com/form-cma.php

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Naples Home?"
    CTA_text2: "Search the entire MLS for your Naples home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://napoleonluxuryrealestate.idxbroker.com/idx/search/advanced

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/NapoleonLuxuryRealEstate
  linkedin_url: https://www.linkedin.com/in/vincent-napoleon-a461469
  youtube_url: https://www.youtube.com/channel/UCqHepCG-VAPzZIoswFbnnqg?view_as=subscriber
  twitter_url: https://twitter.com/askvincent
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/naples-real-estate-podcast-with-vincent-napoleon/id1481101664

podcast:
  title: 'Naples Real Estate Podcast with Vincent Napoleon'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Naples Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Napoleon Luxury Real Estate - your professional Naples Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Naples, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Vincent Napoleon'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Naples Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
